### ISSUE TITLE
npm install - Release/obj.target/keccak/src/addon.o failed

### ISSUE THREAD

**Issue by tpmccallum** [Uniswap/uniswap-interface#1105]
**Bug Description**
Just an error during installation 

**Steps to Reproduce**
npm install
...

**Error**
```
keccak.target.mk:129: recipe for target 'Release/obj.target/keccak/src/addon.o' failed
make: *** [Release/obj.target/keccak/src/addon.o] Error 1
make: Leaving directory '/media/nvme/uniswap-interface/node_modules/ethereumjs-util/node_modules/keccak/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-1034-aws
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/nvme/uniswap-interface/node_modules/ethereumjs-util/node_modules/keccak
gyp ERR! node -v v12.18.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-09-16T03_28_49_153Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.
```
Interestingly the installation kept going after this point with the message
```
Keccak bindings compilation fail. Pure JS implementation will be used.
```
Not sure how much of a problem this is, just sharing :)

**Comment by moodysalem** [comment]
use yarn which ignores scripts
