### ISSUE TITLE
Class constructor Parser cannot be invoked without 'new'

### ISSUE THREAD

**Issue by tpmccallum** [Uniswap/uniswap-interface#1109]
**Bug Description**
Installer is failing with the error message `Class constructor Parser cannot be invoked without 'new'`

**Steps to Reproduce**
```
npm run build
```
or 
```
yarn run build
```
...

**Results**
```
npm run build
> @uniswap/interface@ build /home/ubuntu/new_oasis/uniswap-interface
> react-scripts build
Creating an optimized production build...
Failed to compile.
Class constructor Parser cannot be invoked without 'new'
```

This is the debug log

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v10.19.0/bin/node',
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v10.19.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.13.4
3 info using node@v10.19.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @uniswap/interface@~prebuild: @uniswap/interface@
6 info lifecycle @uniswap/interface@~build: @uniswap/interface@
7 verbose lifecycle @uniswap/interface@~build: unsafe-perm in lifecycle true
8 verbose lifecycle @uniswap/interface@~build: PATH: /home/ubuntu/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/new_oasis/uniswap-interface/node_modules/.bin:/home/ubuntu/.cargo/bin:/home/ubuntu/.nvm/versions/node/v10.19.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle @uniswap/interface@~build: CWD: /home/ubuntu/new_oasis/uniswap-interface
10 silly lifecycle @uniswap/interface@~build: Args: [ '-c', 'react-scripts build' ]
11 silly lifecycle @uniswap/interface@~build: Returned: code: 1  signal: null
12 info lifecycle @uniswap/interface@~build: Failed to exec build script
13 verbose stack Error: @uniswap/interface@ build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/ubuntu/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/ubuntu/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @uniswap/interface@
15 verbose cwd /home/ubuntu/new_oasis/uniswap-interface
16 verbose Linux 5.3.0-1034-aws
17 verbose argv "/home/ubuntu/.nvm/versions/node/v10.19.0/bin/node" "/home/ubuntu/.nvm/versions/node/v10.19.0/bin/npm" "run" "build"
18 verbose node v10.19.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error @uniswap/interface@ build: `react-scripts build`
22 error Exit status 1
23 error Failed at the @uniswap/interface@ build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Thank you

**Comment by tpmccallum** [comment]
I think I found the solution to this.
I used `yarn` and then `yarn run build` as apposed to what was causing me the issue (i.e. the original `npm install` and `npm run build` approach).
