### ISSUE TITLE
Crash report WETH->ETH selection in WETH - LINK pool

### ISSUE THREAD

**Issue by zorrikvoldman** [Uniswap/uniswap-interface#1508]
**Bug Description**
  
App crashed

**Steps to Reproduce**

1. Go to ...
2. Click on ...
   ...
   
**Error**

```
Error: Invariant failed
```

**Stacktrace**

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:98269)
    at t.r.sortsBefore (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:2403)
    at Oy (https://app.uniswap.org/static/js/main.1cc75114.chunk.js:1:321131)
    at no (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1472614)
    at zo (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1482181)
    at Vs (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1526063)
    at Au (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1512246)
    at Su (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1512174)
    at Tu (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1512037)
    at mu (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1509003)
```

**Device data**

```json5
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.93",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.93"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by moodysalem** [comment]
repro steps:
1. visit https://app.uniswap.org/#/add/ETH/0x514910771AF9Ca656af840dff83E8264EcF986CA
2. click ETH select
3. search 'WETH' and pick WETH
