### ISSUE TITLE
Crash report: `Failed to execute 'removeChild' on 'Node'`

### ISSUE THREAD

**Issue by Andrey22S** [Uniswap/uniswap-interface#1512]
**Bug Description**
  
App crashed

**Steps to Reproduce**

1. Go to ...
2. Click on ...
   ...
   
**Error**

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

**Stacktrace**

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1503372)
    at Cu (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1515184)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1535801)
    at Hi (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1458159)
    at Pu (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1513142)
    at mu (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1509228)
    at https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1458382
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1535801)
    at Hi (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1458159)
    at Xi (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1458327)
```

**Device data**

```json5
{
  "ua": "Mozilla/5.0 (Linux; Android 9; ASUS_X00TD) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.91 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.91",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.91"
  },
  "os": {
    "name": "Android",
    "version": "9"
  },
  "device": {
    "vendor": "ASUS",
    "model": "X00TD",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by moodysalem** [comment]
can you share what you were doing when you saw this error?

**Comment by NoahZinsmeister** [comment]
@justindomingue this might be a good issue for you to investigate?

**Comment by Rony859** [comment]
good evening I have a problem to retrieve the airdrop uniswap v2 can help me

**Comment by moodysalem** [comment]
not seeing reports of this anymore, will wait for a report with a url/state dump
