### ISSUE TITLE
Crash report: `t`

### ISSUE THREAD

**Issue by christovski** [Uniswap/uniswap-interface#1520]
**Bug Description**
  
App crashed

**Steps to Reproduce**

1. I think I tried to create a liquidity position with a very small amount of a token in v2. 
2. Create new liquidity position (pool) by navigating in browser to v2 liquidity 
3. select ETH as prime token, and ER20 token as secondary 
4. Select max amount on the ER20 token
   ...
   
**Error**

```
t
```

**Stacktrace**

```
t
    at e.t.getLiquidityMinted (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:88268)
    at https://app.uniswap.org/static/js/main.1cc75114.chunk.js:1:522644
    at Object.Eo [as useMemo] (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1477347)
    at t.useMemo (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1396801)
    at https://app.uniswap.org/static/js/main.1cc75114.chunk.js:1:522535
    at oS (https://app.uniswap.org/static/js/main.1cc75114.chunk.js:1:523520)
    at no (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1472614)
    at zo (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1482181)
    at Vs (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1526063)
    at Au (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1512246)
```

**Device data**

```json5
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.93",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.93"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.13.6"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by moodysalem** [comment]
relevant LOC
https://github.com/Uniswap/uniswap-interface/blob/27960532ca61c56261c1998efac5fb619f897711/src/state/mint/hooks.ts#L160

**Comment by justindomingue** [comment]
Can repro locally by setting token amount to a very small number (just .000000..0001). Error thrown is InsufficientInputAmountError.

**Comment by justindomingue** [comment]
Reopening. Had to revert the fix.
