### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by jiivii252** [Uniswap/uniswap-interface#1529]
**Bug Description**
  
App crashed

**Steps to Reproduce**

1. Go to ...
2. Click on ...
   ...
   
**Error**

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

**Stacktrace**

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1503372)
    at Cu (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1515184)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1535801)
    at Hi (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1458159)
    at Pu (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1513142)
    at mu (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1509228)
    at https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1458382
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1535801)
    at Hi (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1458159)
    at Xi (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1458327)
```

**Device data**

```json5
{
  "ua": "Mozilla/5.0 (Linux; Android 8.1.0; CPH1909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "89.0.4389.105",
    "major": "89"
  },
  "engine": {
    "name": "Blink",
    "version": "89.0.4389.105"
  },
  "os": {
    "name": "Android",
    "version": "8.1.0"
  },
  "device": {
    "vendor": "OPPO",
    "model": "CPH1909",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by NoahZinsmeister** [comment]
tracking in #1512
