### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by friley224** [Uniswap/uniswap-interface#1547]
**Bug Description**
  
App crashed

**Steps to Reproduce**

1. Go to ...
2. Click on ...
   ...
   
**Error**

```
Error: Invariant failed
```

**Stacktrace**

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.d6a485e3.chunk.js:2:84980)
    at e.t.toSignificant (https://app.uniswap.org/static/js/4.d6a485e3.chunk.js:2:31051)
    at t.r.toSignificant (https://app.uniswap.org/static/js/4.d6a485e3.chunk.js:2:32969)
    at kv (https://app.uniswap.org/static/js/main.75c59955.chunk.js:1:287157)
    at Wv (https://app.uniswap.org/static/js/main.75c59955.chunk.js:1:293717)
    at no (https://app.uniswap.org/static/js/4.d6a485e3.chunk.js:2:1481108)
    at zo (https://app.uniswap.org/static/js/4.d6a485e3.chunk.js:2:1490675)
    at Vs (https://app.uniswap.org/static/js/4.d6a485e3.chunk.js:2:1534557)
    at Au (https://app.uniswap.org/static/js/4.d6a485e3.chunk.js:2:1520740)
    at Su (https://app.uniswap.org/static/js/4.d6a485e3.chunk.js:2:1520668)
```

**Device data**

```json5
{
  "ua": "Mozilla/5.0 (Linux; Android 10; Android SDK built for x86 Build/OSM1.180201.023) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "77.0.3865.92",
    "major": "77"
  },
  "engine": {
    "name": "Blink",
    "version": "77.0.3865.92"
  },
  "os": {
    "name": "Android",
    "version": "10"
  },
  "device": {
    "model": "Android SDK built for x86",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by moodysalem** [comment]
fixed by https://github.com/Uniswap/uniswap-interface/commit/7d45ff5ca8fb3c512d89875ba97d1c57e7a72219 releasing now
