### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by jgrebski** [Uniswap/uniswap-interface#1554]
**Bug Description**
  
App crashed

**Steps to Reproduce**

1. Go to ...
2. Click on ...
   ...

**URL**

https://app.uniswap.org/#/swap?use=V2

**Error**

```
Error: Invariant failed
```

**Stacktrace**

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.7fda793a.chunk.js:2:84980)
    at e.t.toSignificant (https://app.uniswap.org/static/js/4.7fda793a.chunk.js:2:31051)
    at t.r.toSignificant (https://app.uniswap.org/static/js/4.7fda793a.chunk.js:2:32969)
    at kv (https://app.uniswap.org/static/js/main.eb6c90bc.chunk.js:1:287201)
    at Wv (https://app.uniswap.org/static/js/main.eb6c90bc.chunk.js:1:293761)
    at no (https://app.uniswap.org/static/js/4.7fda793a.chunk.js:2:1481097)
    at zo (https://app.uniswap.org/static/js/4.7fda793a.chunk.js:2:1490664)
    at Vs (https://app.uniswap.org/static/js/4.7fda793a.chunk.js:2:1534546)
    at Au (https://app.uniswap.org/static/js/4.7fda793a.chunk.js:2:1520729)
    at Su (https://app.uniswap.org/static/js/4.7fda793a.chunk.js:2:1520657)
```

**Device data**

```json5
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.93",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.93"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by moodysalem** [comment]
fixed by https://github.com/Uniswap/uniswap-interface/commit/7d45ff5ca8fb3c512d89875ba97d1c57e7a72219 releasing now
