### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by Jodel55** [Uniswap/uniswap-interface#1556]
**Bug Description**
  
App crashed

**Steps to Reproduce**

1. Go to ...
2. Click on ...
   ...

**URL**

https://app.uniswap.org/#/swap?outputCurrency=0x3301ee63fb29f863f2333bd4466acb46cd8323e6

**Error**

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

**Stacktrace**

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1511855)
    at Cu (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1523667)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1544284)
    at Hi (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1466642)
    at Pu (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1521625)
    at bu (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1517711)
    at https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1466865
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1544284)
    at Hi (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1466642)
    at Xi (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1466810)
```

**Device data**

```json5
{
  "ua": "Mozilla/5.0 (Linux; Android 8.1.0; DUB-LX3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.210 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.210",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.210"
  },
  "os": {
    "name": "Android",
    "version": "8.1.0"
  },
  "device": {
    "model": "DUB-LX3",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by NoahZinsmeister** [comment]
tracking in #1512
