### ISSUE TITLE
Crash report: `Error: Addresses should not be equal`

### ISSUE THREAD

**Issue by zorrikvoldman** [Uniswap/uniswap-interface#1558]
**Bug Description**
  
App crashed

**Steps to Reproduce**

1. Go to ...
2. Click on ...
   ...

**URL**

https://app.uniswap.org/#/add/ETH/0x2260fac5e5542a773aa44fbcfedf7c193bc2c599

**Error**

```
Error: Addresses should not be equal
```

**Stacktrace**

```
Error: Addresses should not be equal
    at e.value (https://app.uniswap.org/static/js/main.8d689671.chunk.js:1:70344)
    at Ay (https://app.uniswap.org/static/js/main.8d689671.chunk.js:1:324622)
    at no (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1481097)
    at zo (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1490664)
    at Vs (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1534546)
    at Au (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1520729)
    at Su (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1520657)
    at Tu (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1520520)
    at bu (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1517486)
    at https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1466865
```

**Device data**

```json5
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.212",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.212"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by NoahZinsmeister** [comment]
tracking in #1557
