### ISSUE TITLE
Crash report: `RangeError: Division by zero`

### ISSUE THREAD

**Issue by Alex-Alive** [Uniswap/uniswap-interface#1559]
**Bug Description**
  
App crashed

**Steps to Reproduce**

1. Go to ...
2. Click on ...
   ...

**URL**

https://app.uniswap.org/#/add/v2/ETH/0x5799Fc4D6dB5d7C93a9d9EF10dF363d346988A58

**Error**

```
RangeError: Division by zero
```

**Stacktrace**

```
RangeError: Division by zero
    at Function.value (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:46528)
    at t.get (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:31545)
    at new t (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:31890)
    at Function.t.fromFractionalAmount (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:32113)
    at t.r.divide (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:32772)
    at e.get (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:238684)
    at e.t.priceOf (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:235699)
    at https://app.uniswap.org/static/js/main.8d689671.chunk.js:1:525377
    at Object.Eo [as useMemo] (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1485830)
    at t.useMemo (https://app.uniswap.org/static/js/4.5121d2e8.chunk.js:2:1405284)
```

**Device data**

```json5
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.93",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.93"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by NoahZinsmeister** [comment]
tracking in #1532
