### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by berrygan** [Uniswap/uniswap-interface#1562]
## URL
  
https://app.uniswap.org/#/add/v2/0x433409d5e7f811a533f251acf1124260d437e990/ETH

## `mint` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "otherTypedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.6e492852.chunk.js:2:1511817)
    at Cu (https://app.uniswap.org/static/js/4.6e492852.chunk.js:2:1523629)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.6e492852.chunk.js:2:1544246)
    at Hi (https://app.uniswap.org/static/js/4.6e492852.chunk.js:2:1466604)
    at Pu (https://app.uniswap.org/static/js/4.6e492852.chunk.js:2:1521587)
    at bu (https://app.uniswap.org/static/js/4.6e492852.chunk.js:2:1517673)
    at https://app.uniswap.org/static/js/4.6e492852.chunk.js:2:1466827
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.6e492852.chunk.js:2:1544246)
    at Hi (https://app.uniswap.org/static/js/4.6e492852.chunk.js:2:1466604)
    at Xi (https://app.uniswap.org/static/js/4.6e492852.chunk.js:2:1466772)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 10; RMX1821) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.210 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.210",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.210"
  },
  "os": {
    "name": "Android",
    "version": "10"
  },
  "device": {
    "model": "RMX1821",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by NoahZinsmeister** [comment]
tracking in #1512
