### ISSUE TITLE
Crash report: `RangeError: Division by zero`

### ISSUE THREAD

**Issue by IntelMin** [Uniswap/uniswap-interface#1578]
## URL
  
https://app.uniswap.org/#/add/v2/ETH/0xc89413FE7e621027aCc057b653c0EF97F63A0566

## `mint` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "otherTypedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
RangeError: Division by zero
```

## Stacktrace

```
RangeError: Division by zero
    at Function.value (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:46138)
    at t.get (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:31155)
    at new t (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:31500)
    at Function.t.fromFractionalAmount (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:31723)
    at t.r.divide (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:32382)
    at e.get (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:238406)
    at e.t.priceOf (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:235421)
    at https://app.uniswap.org/static/js/main.57a68ad3.chunk.js:1:535202
    at Object.Eo [as useMemo] (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1485805)
    at t.useMemo (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1405259)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.212",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.212"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
Thanks IntelMin! We'll track this in the main issue https://github.com/Uniswap/uniswap-interface/issues/1583
