### ISSUE TITLE
Crash report: `RangeError: Division by zero`

### ISSUE THREAD

**Issue by jab416171** [Uniswap/uniswap-interface#1583]
v2 version of #1582 (running on localhost, ae27e24)

## URL
  
http://localhost:3000/#/add/v2/ETH/0x1Faa0c671B6336527efD167F7d1C6Fc1b8A05D1a

## `mint` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "otherTypedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
RangeError: Division by zero
```

## Stacktrace

```
RangeError: Division by zero
    at Function.value (http://localhost:3000/static/js/vendors~main.chunk.js:74070:35)
    at CurrencyAmount.get (http://localhost:3000/static/js/vendors~main.chunk.js:33776:58)
    at new CurrencyAmount (http://localhost:3000/static/js/vendors~main.chunk.js:33803:72)
    at Function.fromFractionalAmount (http://localhost:3000/static/js/vendors~main.chunk.js:33827:12)
    at CurrencyAmount.divide (http://localhost:3000/static/js/vendors~main.chunk.js:33866:27)
    at Pair.get (http://localhost:3000/static/js/vendors~main.chunk.js:35148:41)
    at Pair.priceOf (http://localhost:3000/static/js/vendors~main.chunk.js:35028:64)
    at http://localhost:3000/static/js/main.chunk.js:58979:46
    at updateMemo (http://localhost:3000/static/js/vendors~main.chunk.js:128877:23)
    at Object.useMemo (http://localhost:3000/static/js/vendors~main.chunk.js:129417:20)
    at useMemo (http://localhost:3000/static/js/vendors~main.chunk.js:199356:25)
    at useDerivedMintInfo (http://localhost:3000/static/js/main.chunk.js:58965:70)
    at AddLiquidity (http://localhost:3000/static/js/main.chunk.js:42327:84)
    at renderWithHooks (http://localhost:3000/static/js/vendors~main.chunk.js:128018:22)
    at updateFunctionComponent (http://localhost:3000/static/js/vendors~main.chunk.js:130340:24)
    at beginWork (http://localhost:3000/static/js/vendors~main.chunk.js:131993:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/vendors~main.chunk.js:116968:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/vendors~main.chunk.js:117017:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/vendors~main.chunk.js:117077:35)
    at beginWork$1 (http://localhost:3000/static/js/vendors~main.chunk.js:136819:11)
    at performUnitOfWork (http://localhost:3000/static/js/vendors~main.chunk.js:135655:16)
    at workLoopSync (http://localhost:3000/static/js/vendors~main.chunk.js:135592:9)
    at renderRootSync (http://localhost:3000/static/js/vendors~main.chunk.js:135558:11)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/vendors~main.chunk.js:135175:22)
    at http://localhost:3000/static/js/vendors~main.chunk.js:124428:30
    at unstable_runWithPriority (http://localhost:3000/static/js/vendors~main.chunk.js:203808:16)
    at runWithPriority$1 (http://localhost:3000/static/js/vendors~main.chunk.js:124374:14)
    at flushSyncCallbackQueueImpl (http://localhost:3000/static/js/vendors~main.chunk.js:124423:13)
    at flushSyncCallbackQueue (http://localhost:3000/static/js/vendors~main.chunk.js:124411:7)
    at batchedUpdates$1 (http://localhost:3000/static/js/vendors~main.chunk.js:135269:11)
    at Object.notify (http://localhost:3000/static/js/vendors~main.chunk.js:186243:7)
    at Subscription.notifyNestedSubs (http://localhost:3000/static/js/vendors~main.chunk.js:186314:20)
    at Subscription.handleChangeWrapper (http://localhost:3000/static/js/vendors~main.chunk.js:186319:12)
    at dispatch (http://localhost:3000/static/js/vendors~main.chunk.js:201210:7)
    at http://localhost:3000/static/js/vendors~main.chunk.js:200787:17
    at http://localhost:3000/static/js/vendors~main.chunk.js:30866:22
    at http://localhost:3000/static/js/vendors~main.chunk.js:30715:32
    at http://localhost:3000/static/js/main.chunk.js:61019:48
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.93",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.93"
  },
  "os": {
    "name": "Linux",
    "version": "x86_64"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by jab416171** [comment]
looking through the code, I added some logging on line 134 in https://github.com/Uniswap/uniswap-interface/blob/main/src/state/mint/hooks.ts (line 148 is where the division by zero is thrown)

`noLiquidity` is false, `pairState` is 0, and `totalSupply` is undefined
noLiquidity should be true, since this is a brand new pair

**Comment by jab416171** [comment]
I have another example here:
http://localhost:3000/#/add/v2/ETH/0x283e8d5c44918583698e003b7e0b81fa3d939f18
for testing I created this token list: 
https://gist.githubusercontent.com/jab416171/998c006846573dc7f51e7278f0b8aa0b/raw/93a8ba4e78ee6ae208efd1a0d1b883c302364daa/tokenlist.json

**Comment by jab416171** [comment]
As an extra note it doesn't matter if you have the tokens in your wallet, the same bug is still triggered.

**Comment by likes** [comment]
Having the same issue since 16th when I add my coin address to adding Liq on V2 

Something went wrong
RangeError: Division by zero
    at Function.value (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:46138)
    at t.get (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:31155)
    at new t (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:31500)
    at Function.t.fromFractionalAmount (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:31723)
    at t.r.divide (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:32382)
    at e.get (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:238244)
    at e.t.priceOf (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:235404)
    at https://app.uniswap.org/static/js/main.43299ced.chunk.js:1:535698
    at Object.Eo [as useMemo] (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1485805)
    at t.useMemo (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1405259)

**Comment by ericwingate** [comment]
Also having this same issue.. hopefully this can get patched quick!

**Comment by willhennessy** [comment]
The reporter filed this bug (1583) for the error in v2, and this other bug (1582) for a similar error in v3 though slightly different stack trace. Can you ptal at https://github.com/Uniswap/uniswap-interface/issues/1582 to see if it's the same issue?

**Comment by ericwingate** [comment]
I was using v2, not sure if its the same in v3.

**Comment by aress31** [comment]
Well having this issue too on V2 appeared out of the blue! Can we please get a quick fix!

**Comment by Tweetster999** [comment]
FYI: The issue persists on v2 add liquidity for me.

**Comment by erience** [comment]
Apart from this What can be done for removing the liquidity of deflationery tokens?

**Comment by erience** [comment]
@NoahZinsmeister

**Comment by aress31** [comment]
This issue hasnt been fixed for me!

**Comment by jab416171** [comment]
Thank you @justindomingue!
@aress31 please wait for a new release to go out, you can follow [this](https://github.com/uniswap/uniswap-interface/releases) for releases, or try the preview version of uniswap [here](https://uniswap-interface-git-divide-0-uniswap.vercel.app/)
