### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by yangxianming07** [Uniswap/uniswap-interface#1586]
## URL
  
https://app.uniswap.org/#/swap?inputCurrency=0x56015bbe3c01fe05bc30a8a9a9fd9a88917e7db3&outputCurrency=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0x56015BBE3C01fE05bc30A8a9a9Fd9A88917e7dB3"
  },
  "OUTPUT": {
    "currencyId": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1511830)
    at Cu (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1523642)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1544259)
    at Hi (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466617)
    at Pu (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1521600)
    at bu (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1517686)
    at https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466840
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1544259)
    at Hi (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466617)
    at Xi (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466785)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "89.0.4389.114",
    "major": "89"
  },
  "engine": {
    "name": "Blink",
    "version": "89.0.4389.114"
  },
  "os": {
    "name": "Windows",
    "version": "7"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
Thanks yangwianming07! Referencing this issue in the main tracker https://github.com/Uniswap/uniswap-interface/issues/1576
