### ISSUE TITLE
Crash report: `RangeError: Division by zero`

### ISSUE THREAD

**Issue by makerzy** [Uniswap/uniswap-interface#1587]
## URL
  
https://app.uniswap.org/#/add/v2/ETH/0xfaB29dDFe489ca151476c75020904C3567fc63F4

## `mint` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "otherTypedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
RangeError: Division by zero
```

## Stacktrace

```
RangeError: Division by zero
    at Function.value (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:46138)
    at t.get (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:31155)
    at new t (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:31500)
    at Function.t.fromFractionalAmount (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:31723)
    at t.r.divide (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:32382)
    at e.get (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:238244)
    at e.t.priceOf (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:235404)
    at https://app.uniswap.org/static/js/main.43299ced.chunk.js:1:535698
    at Object.Eo [as useMemo] (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1485805)
    at t.useMemo (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1405259)
```

**Comment by willhennessy** [comment]
Thanks makerzy! We'll track this in the main issue https://github.com/Uniswap/uniswap-interface/issues/1583
