### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by sonneferrr** [Uniswap/uniswap-interface#1590]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0x276ceb4052c5add844ab14bf2c5efa5addc9ef22

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": ""
  },
  "OUTPUT": {
    "currencyId": "0x276ceb4052C5aDd844AB14bF2c5efa5Addc9ef22"
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1511830)
    at Cu (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1523642)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1544259)
    at Hi (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466617)
    at Pu (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1521600)
    at bu (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1517686)
    at https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466840
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1544259)
    at Hi (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466617)
    at Xi (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466785)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 10; CPH1979) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.210 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.210",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.210"
  },
  "os": {
    "name": "Android",
    "version": "10"
  },
  "device": {
    "vendor": "OPPO",
    "model": "CPH1979",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
Thanks sonneferrr! Referencing this issue in the main tracker https://github.com/Uniswap/uniswap-interface/issues/1576
