### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by AIDASJ** [Uniswap/uniswap-interface#1602]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE"
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1511830)
    at Cu (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1523642)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1544259)
    at Hi (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466617)
    at Pu (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1521600)
    at bu (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1517686)
    at https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466840
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1544259)
    at Hi (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466617)
    at Xi (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466785)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "88.0.4324.192",
    "major": "88"
  },
  "engine": {
    "name": "Blink",
    "version": "88.0.4324.192"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.13.6"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
Thanks AIDASJ! Referencing this issue in the main tracker https://github.com/Uniswap/uniswap-interface/issues/1576
