### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by Moreno9595** [Uniswap/uniswap-interface#1603]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0x761d38e5ddf6ccf6cf7c55759d5210750b5d60f3

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0xB8c77482e45F1F44dE1745F52C74426C631bDD52"
  },
  "OUTPUT": {
    "currencyId": "0x761D38e5ddf6ccf6Cf7c55759d5210750B5D60F3"
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1511830)
    at Cu (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1523642)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1544259)
    at Hi (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466617)
    at Pu (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1521600)
    at bu (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1517686)
    at https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466840
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1544259)
    at Hi (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466617)
    at Xi (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466785)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 9; CLT-L09) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "89.0.4389.105",
    "major": "89"
  },
  "engine": {
    "name": "Blink",
    "version": "89.0.4389.105"
  },
  "os": {
    "name": "Android",
    "version": "9"
  },
  "device": {
    "vendor": "Huawei",
    "model": "CLT-L09",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
Thanks Moreno9595! Referencing this issue in the main tracker https://github.com/Uniswap/uniswap-interface/issues/1576
