### ISSUE TITLE
Crash report: `Error: Addresses should not be equal`

### ISSUE THREAD

**Issue by Bloodshotf15** [Uniswap/uniswap-interface#1605]
## URL
  
https://app.uniswap.org/#/add/ETH/0xdac17f958d2ee523a2206206994597c13d831ec7

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "3401.6",
  "rightRangeTypedValue": ""
}
```

## Error

```
Error: Addresses should not be equal
```

## Stacktrace

```
Error: Addresses should not be equal
    at e.value (https://app.uniswap.org/static/js/main.43299ced.chunk.js:1:71493)
    at kO (https://app.uniswap.org/static/js/main.43299ced.chunk.js:1:333551)
    at no (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1481072)
    at zo (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1490639)
    at Vs (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1534521)
    at Au (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1520704)
    at Su (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1520632)
    at Tu (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1520495)
    at bu (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1517461)
    at https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1466840
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.212",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.212"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by justindomingue** [comment]
@Bloodshotf15 are you able to provide repro steps?

**Comment by moodysalem** [comment]
This is fixed
