### ISSUE TITLE
Crash report: `RangeError: Division by zero`

### ISSUE THREAD

**Issue by pcatana** [Uniswap/uniswap-interface#1607]
## URL
  
http://uniswap.eth.link.ipns.localhost:48084/#/add/v2/0x7419f744bBF35956020C1687fF68911cD777f865/0x4F96Fe3b7A6Cf9725f59d353F723c1bDb64CA6Aa

## `mint` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "otherTypedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
RangeError: Division by zero
```

## Stacktrace

```
RangeError: Division by zero
    at Function.value (http://uniswap.eth.link.ipns.localhost:48084/static/js/4.dcf5ab76.chunk.js:2:46138)
    at t.get (http://uniswap.eth.link.ipns.localhost:48084/static/js/4.dcf5ab76.chunk.js:2:31155)
    at new t (http://uniswap.eth.link.ipns.localhost:48084/static/js/4.dcf5ab76.chunk.js:2:31500)
    at Function.t.fromFractionalAmount (http://uniswap.eth.link.ipns.localhost:48084/static/js/4.dcf5ab76.chunk.js:2:31723)
    at t.r.divide (http://uniswap.eth.link.ipns.localhost:48084/static/js/4.dcf5ab76.chunk.js:2:32382)
    at e.get (http://uniswap.eth.link.ipns.localhost:48084/static/js/4.dcf5ab76.chunk.js:2:238406)
    at e.t.priceOf (http://uniswap.eth.link.ipns.localhost:48084/static/js/4.dcf5ab76.chunk.js:2:235421)
    at http://uniswap.eth.link.ipns.localhost:48084/static/js/main.43299ced.chunk.js:1:535698
    at Object.Eo [as useMemo] (http://uniswap.eth.link.ipns.localhost:48084/static/js/4.dcf5ab76.chunk.js:2:1485805)
    at t.useMemo (http://uniswap.eth.link.ipns.localhost:48084/static/js/4.dcf5ab76.chunk.js:2:1405259)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.93",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.93"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
Thanks pcatana! We'll track this in the main issue https://github.com/Uniswap/uniswap-interface/issues/1583
