### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by pdinkins** [Uniswap/uniswap-interface#1608]
## URL
  
https://app.uniswap.org/#/add/ETH/0x5218E472cFCFE0b64A064F055B43b4cdC9EfD3A6/10000

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "0",
  "rightRangeTypedValue": "34437820000000000000000000000000000000000"
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:84926)
    at Function.e.getTickAtSqrtRatio (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1885386)
    at t.priceToClosestTick (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1914410)
    at cO (https://app.uniswap.org/static/js/main.43299ced.chunk.js:1:321384)
    at https://app.uniswap.org/static/js/main.43299ced.chunk.js:1:323803
    at Object.Eo [as useMemo] (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1485805)
    at t.useMemo (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1405259)
    at lO (https://app.uniswap.org/static/js/main.43299ced.chunk.js:1:323676)
    at xg (https://app.uniswap.org/static/js/main.43299ced.chunk.js:1:348762)
    at no (https://app.uniswap.org/static/js/4.dcf5ab76.chunk.js:2:1481072)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.212",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.212"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
Hi pdinkins, thanks for filing! We're working this at https://github.com/Uniswap/uniswap-interface/issues/1571
