### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by nobu-sys** [Uniswap/uniswap-interface#1629]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": ""
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1512234)
    at Cu (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1524046)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1544663)
    at Hi (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1467021)
    at Pu (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1522004)
    at bu (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1518090)
    at https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1467244
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1544663)
    at Hi (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1467021)
    at Xi (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1467189)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (X11; CrOS x86_64 13816.80.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.215 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.215",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.215"
  },
  "os": {
    "name": "Chromium OS",
    "version": "13816.80.0"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by justindomingue** [comment]
@nobu-sys is it a consistent repro for you?

**Comment by willhennessy** [comment]
Thanks nobu-sys! If you can repro, please reply on the de-duped issue https://github.com/Uniswap/uniswap-interface/issues/1576
