### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by Migel1982** [Uniswap/uniswap-interface#1630]
## URL
  
https://app.uniswap.org/#/add/v2/0x961C8c0B1aaD0c0b10a51FeF6a867E3091BCef17/ETH

## `mint` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "otherTypedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1512234)
    at Cu (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1524046)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1544663)
    at Hi (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1467021)
    at Pu (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1522004)
    at bu (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1518090)
    at https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1467244
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1544663)
    at Hi (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1467021)
    at Xi (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1467189)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.212",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.212"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by justindomingue** [comment]
@Migel1982 does it repro consistently for you? Any other details to help debug?

**Comment by willhennessy** [comment]
Thanks Migel1982! If you can repro, please reply on the de-duped issue https://github.com/Uniswap/uniswap-interface/issues/1576
