### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by mqg1232** [Uniswap/uniswap-interface#1631]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": ""
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1512234)
    at Cu (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1524046)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1544663)
    at Hi (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1467021)
    at Pu (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1522004)
    at bu (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1518090)
    at https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1467244
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1544663)
    at Hi (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1467021)
    at Xi (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1467189)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4484.7 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "92.0.4484.7",
    "major": "92"
  },
  "engine": {
    "name": "Blink",
    "version": "92.0.4484.7"
  },
  "os": {
    "name": "Windows",
    "version": "7"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by justindomingue** [comment]
@mqg1232  does it repro consistently for you? Any other details to help debug?

**Comment by willhennessy** [comment]
Thanks mqg1232! If you can repro, please reply on the de-duped issue https://github.com/Uniswap/uniswap-interface/issues/1576
