### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by Danpi3141** [Uniswap/uniswap-interface#1649]
## URL
  
https://app.uniswap.org/#/add/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "2500",
  "rightRangeTypedValue": "8000"
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:84926)
    at t.r.sortsBefore (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:35227)
    at kO (https://app.uniswap.org/static/js/main.2221a832.chunk.js:1:333797)
    at no (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1481476)
    at zo (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1491043)
    at Vs (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1534925)
    at Au (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1521108)
    at Su (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1521036)
    at Tu (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1520899)
    at bu (https://app.uniswap.org/static/js/4.6e0ef0a0.chunk.js:2:1517865)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.212",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.212"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

I was depositing ETH/USDC set up my price limits of 2500 & 8000, then when I decided to change from ETH to WETH this error occurred, not a big deal, I'll try again setting to WETH before setting the price limits.

**Comment by moodysalem** [comment]
I believe this is fixed now
