### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by hasan245** [Uniswap/uniswap-interface#1655]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0xe4cfe9eaa8cdb0942a80b7bc68fd8ab0f6d44903&use=V2

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": ""
  },
  "OUTPUT": {
    "currencyId": "ETH"
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1512461)
    at Cu (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1524273)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1544890)
    at Hi (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1467248)
    at Pu (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1522231)
    at bu (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1518317)
    at https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1467471
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1544890)
    at Hi (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1467248)
    at Xi (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1467416)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 8.0.0; SM-A520F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.210 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.210",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.210"
  },
  "os": {
    "name": "Android",
    "version": "8.0.0"
  },
  "device": {
    "vendor": "Samsung",
    "model": "SM-A520F",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
Thanks hasan245! We're investigating this in #1576!
