### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by ibraimamanda** [Uniswap/uniswap-interface#1670]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0xD657D92615C75e1D2E80342246BF759E431d3F2F"
  },
  "independentField": "OUTPUT",
  "typedValue": "1",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1511898)
    at Cu (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1523710)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1544327)
    at Hi (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1466685)
    at Pu (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1521668)
    at bu (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1517754)
    at https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1466908
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1544327)
    at Hi (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1466685)
    at Xi (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1466853)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.212",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.212"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by justindomingue** [comment]
@ibraimamanda does it repro consistently for you? Any extra repro steps / extensions / setup instructions?

**Comment by willhennessy** [comment]
If you can reproduce, please comment in #1576!
