### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by cathrienli** [Uniswap/uniswap-interface#1673]
## URL
  
https://app.uniswap.org/#/swap?inputCurrency=ETH&outputCurrency=0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0xdAC17F958D2ee523a2206206994597C13D831ec7"
  },
  "OUTPUT": {
    "currencyId": "0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE"
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1511898)
    at Cu (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1523710)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1544327)
    at Hi (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1466685)
    at Pu (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1521668)
    at bu (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1517754)
    at https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1466908
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1544327)
    at Hi (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1466685)
    at Xi (https://app.uniswap.org/static/js/4.71b529b3.chunk.js:2:1466853)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.212",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.212"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by justindomingue** [comment]
Thanks @cathrienli . Does it repro consistently for you?

**Comment by willhennessy** [comment]
If you can reproduce, please comment in #1576!
