### ISSUE TITLE
クラッシュ レポート: 'NotFoundError: 'ノード' で 'removeChild' を実行できませんでした: 削除するノードはこのノードの子ではありません。

### ISSUE THREAD

**Issue by MasayasuIchimura** [Uniswap/uniswap-interface#1720]
## URL
  
https://app.uniswap.org/#/swap?use=V2

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0x7FF4169a6B5122b664c51c95727d87750eC07c84"
  },
  "independentField": "INPUT",
  "typedValue": "0.4",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1509774)
    at ju (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1521586)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1542203)
    at Hi (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1464561)
    at Pu (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1519544)
    at mu (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1515630)
    at https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1464784
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1542203)
    at Hi (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1464561)
    at Xi (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1464729)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Edg/90.0.818.66",
  "browser": {
    "name": "Edge",
    "version": "90.0.818.66",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.212"
  },
  "os": {
    "name": "Windows",
    "version": "7"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by moodysalem** [comment]
Duplicate of https://github.com/Uniswap/uniswap-interface/issues/1576
