### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by AlbertoValentin** [Uniswap/uniswap-interface#1763]
## URL
  
https://app.uniswap.org/#/add/ETH/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:85152)
    at t.r.sortsBefore (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:72944)
    at https://app.uniswap.org/static/js/main.236a68a4.chunk.js:1:312595
    at Object.Ao [as useMemo] (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1483749)
    at t.useMemo (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1403203)
    at vO (https://app.uniswap.org/static/js/main.236a68a4.chunk.js:1:312568)
    at Rg (https://app.uniswap.org/static/js/main.236a68a4.chunk.js:1:338752)
    at no (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1479016)
    at zo (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1488583)
    at Vs (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1532465)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.212",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.212"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by moodysalem** [comment]
Bug is adding liquidity in ETH + WETH causing a JS error
