### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by onie92** [Uniswap/uniswap-interface#1784]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": ""
  },
  "OUTPUT": {
    "currencyId": "ETH"
  },
  "independentField": "OUTPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.9957cdd2.chunk.js:2:1500044)
    at Cu (https://app.uniswap.org/static/js/4.9957cdd2.chunk.js:2:1511856)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.9957cdd2.chunk.js:2:1532473)
    at Hi (https://app.uniswap.org/static/js/4.9957cdd2.chunk.js:2:1454831)
    at Pu (https://app.uniswap.org/static/js/4.9957cdd2.chunk.js:2:1509814)
    at mu (https://app.uniswap.org/static/js/4.9957cdd2.chunk.js:2:1505900)
    at https://app.uniswap.org/static/js/4.9957cdd2.chunk.js:2:1455054
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.9957cdd2.chunk.js:2:1532473)
    at Hi (https://app.uniswap.org/static/js/4.9957cdd2.chunk.js:2:1454831)
    at Xi (https://app.uniswap.org/static/js/4.9957cdd2.chunk.js:2:1454999)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 10; CPH1933) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "91.0.4472.77",
    "major": "91"
  },
  "engine": {
    "name": "Blink",
    "version": "91.0.4472.77"
  },
  "os": {
    "name": "Android",
    "version": "10"
  },
  "device": {
    "vendor": "OPPO",
    "model": "CPH1933",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by onie92** [comment]
> #1829
