### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by shabu1973kerala** [Uniswap/uniswap-interface#1855]
## URL
  
https://app.uniswap.org/#/add/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2/ETH

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.f2b7b943.chunk.js:2:89844)
    at t.r.sortsBefore (https://app.uniswap.org/static/js/4.f2b7b943.chunk.js:2:77637)
    at https://app.uniswap.org/static/js/main.4899fd75.chunk.js:1:320624
    at Object.Eo [as useMemo] (https://app.uniswap.org/static/js/4.f2b7b943.chunk.js:2:1477991)
    at t.useMemo (https://app.uniswap.org/static/js/4.f2b7b943.chunk.js:2:1397463)
    at NO (https://app.uniswap.org/static/js/main.4899fd75.chunk.js:1:320597)
    at qv (https://app.uniswap.org/static/js/main.4899fd75.chunk.js:1:347860)
    at no (https://app.uniswap.org/static/js/4.f2b7b943.chunk.js:2:1473258)
    at zo (https://app.uniswap.org/static/js/4.f2b7b943.chunk.js:2:1482825)
    at Vs (https://app.uniswap.org/static/js/4.f2b7b943.chunk.js:2:1526707)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 10; SM-N960F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "87.0.4280.101",
    "major": "87"
  },
  "engine": {
    "name": "Blink",
    "version": "87.0.4280.101"
  },
  "os": {
    "name": "Android",
    "version": "10"
  },
  "device": {
    "vendor": "Samsung",
    "model": "SM-N960F",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
thanks for filing! we're tracking this in 1763
