### ISSUE TITLE
Crash report: `TypeError: Cannot read property 'description' of undefined`

### ISSUE THREAD

**Issue by ecuevas91** [Uniswap/uniswap-interface#1878]
## URL
  
https://app.uniswap.org/#/vote

## Error

```
TypeError: Cannot read property 'description' of undefined
```

## Stacktrace

```
TypeError: Cannot read property 'description' of undefined
    at https://app.uniswap.org/static/js/main.858eeff5.chunk.js:1:520155
    at Array.map (<anonymous>)
    at a (https://app.uniswap.org/static/js/main.858eeff5.chunk.js:1:520097)
    at rk (https://app.uniswap.org/static/js/main.858eeff5.chunk.js:1:531102)
    at kk (https://app.uniswap.org/static/js/main.858eeff5.chunk.js:1:537414)
    at no (https://app.uniswap.org/static/js/4.0254ec1f.chunk.js:2:1473258)
    at zo (https://app.uniswap.org/static/js/4.0254ec1f.chunk.js:2:1482825)
    at Vs (https://app.uniswap.org/static/js/4.0254ec1f.chunk.js:2:1526707)
    at xu (https://app.uniswap.org/static/js/4.0254ec1f.chunk.js:2:1512890)
    at Au (https://app.uniswap.org/static/js/4.0254ec1f.chunk.js:2:1512818)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36 Edg/91.0.864.48",
  "browser": {
    "name": "Edge",
    "version": "91.0.864.48",
    "major": "91"
  },
  "engine": {
    "name": "Blink",
    "version": "91.0.4472.101"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by moodysalem** [comment]
this issue should be fixed by the refactor from a few days ago
