### ISSUE TITLE
Crash report: `TypeError: Object(...)(...).flat is not a function`

### ISSUE THREAD

**Issue by mamiriarfae** [Uniswap/uniswap-interface#1879]
## URL
  
https://app.uniswap.org/#/vote

## Error

```
TypeError: Object(...)(...).flat is not a function
```

## Stacktrace

```
TypeError: Object(...)(...).flat is not a function
    at qn (https://app.uniswap.org/static/js/main.8c9924eb.chunk.js:1:61100)
    at rk (https://app.uniswap.org/static/js/main.8c9924eb.chunk.js:1:520254)
    at kk (https://app.uniswap.org/static/js/main.8c9924eb.chunk.js:1:539119)
    at no (https://app.uniswap.org/static/js/4.6ab7ddf6.chunk.js:2:1473258)
    at Vs (https://app.uniswap.org/static/js/4.6ab7ddf6.chunk.js:2:1525716)
    at xu (https://app.uniswap.org/static/js/4.6ab7ddf6.chunk.js:2:1512890)
    at Au (https://app.uniswap.org/static/js/4.6ab7ddf6.chunk.js:2:1512818)
    at Su (https://app.uniswap.org/static/js/4.6ab7ddf6.chunk.js:2:1512681)
    at mu (https://app.uniswap.org/static/js/4.6ab7ddf6.chunk.js:2:1509647)
    at https://app.uniswap.org/static/js/4.6ab7ddf6.chunk.js:2:1459026
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 6.0.1; SM-J500H Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "56.0.2924.87",
    "major": "56"
  },
  "engine": {
    "name": "Blink",
    "version": "56.0.2924.87"
  },
  "os": {
    "name": "Android",
    "version": "6.0.1"
  },
  "device": {
    "vendor": "Samsung",
    "model": "SM-J500H",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by moodysalem** [comment]
we no longer use .flat, this should be fixed
