### ISSUE TITLE
Crash report: `ReferenceError: Intl is not defined`

### ISSUE THREAD

**Issue by Ruslan2021Horizen** [Uniswap/uniswap-interface#1906]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": ""
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
ReferenceError: Intl is not defined
```

## Stacktrace

```
ReferenceError: Intl is not defined
    at https://app.uniswap.org/static/js/4.2cb6c01a.chunk.js:2:103407
    at https://app.uniswap.org/static/js/4.2cb6c01a.chunk.js:2:104094
    at e (https://app.uniswap.org/static/js/4.2cb6c01a.chunk.js:2:104851)
    at https://app.uniswap.org/static/js/4.2cb6c01a.chunk.js:2:105257
    at Array.reduce (<anonymous>)
    at e (https://app.uniswap.org/static/js/4.2cb6c01a.chunk.js:2:105099)
    at https://app.uniswap.org/static/js/4.2cb6c01a.chunk.js:2:105298
    at r.value (https://app.uniswap.org/static/js/4.2cb6c01a.chunk.js:2:107314)
    at w (https://app.uniswap.org/static/js/4.2cb6c01a.chunk.js:2:2883)
    at no (https://app.uniswap.org/static/js/4.2cb6c01a.chunk.js:2:1473258)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; U; Android 5.1; zh-CN; MZ-m3 note Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 MZBrowser/8.5.110-2021020110 UWS/2.15.0.4 Mobile Safari/537.36",
  "browser": {
    "name": "Android Browser",
    "version": "4.0",
    "major": "4"
  },
  "engine": {
    "name": "Blink",
    "version": "57.0.2987.108"
  },
  "os": {
    "name": "Android",
    "version": "5.1"
  },
  "device": {
    "vendor": "Meizu",
    "model": "m3",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by moodysalem** [comment]
I don't think we use `Intl` anymore, but at one point we used it for formatting numbers with commas and replaced it with the `groupSeparator` setting on Fraction string methods
https://github.com/Uniswap/uniswap-interface/search?q=Intl
