### ISSUE TITLE
Crash report: `TypeError: Cannot read property 'active' of undefined`

### ISSUE THREAD

**Issue by jennypollack** [Uniswap/uniswap-interface#1927]
## URL
  
https://app.uniswap.org/#/uni/0xabc/ETH

## Error

```
TypeError: Cannot read property 'active' of undefined
```

## Stacktrace

```
TypeError: Cannot read property 'active' of undefined
    at Yy (https://app.uniswap.org/static/js/main.3a7392b6.chunk.js:1:400502)
    at no (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1592027)
    at Vu (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1644485)
    at Es (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1631659)
    at As (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1631587)
    at Ss (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1631450)
    at ms (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1628416)
    at https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1577795
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1655214)
    at qi (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1577572)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "91.0.4472.114",
    "major": "91"
  },
  "engine": {
    "name": "Blink",
    "version": "91.0.4472.114"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
Thanks for the PR Luke! Want to follow up on it with moody and release?
