### ISSUE TITLE
Crash report: `TypeError: Object(...)(...).flat is not a function`

### ISSUE THREAD

**Issue by Satnamathwal94** [Uniswap/uniswap-interface#1928]
## URL
  
https://app.uniswap.org/#/vote

## Error

```
TypeError: Object(...)(...).flat is not a function
```

## Stacktrace

```
TypeError: Object(...)(...).flat is not a function
    at _n (https://app.uniswap.org/static/js/main.3a7392b6.chunk.js:1:61190)
    at bI (https://app.uniswap.org/static/js/main.3a7392b6.chunk.js:1:531828)
    at BI (https://app.uniswap.org/static/js/main.3a7392b6.chunk.js:1:550883)
    at no (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1592027)
    at Vu (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1644485)
    at Es (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1631659)
    at As (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1631587)
    at Ss (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1631450)
    at ms (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1628416)
    at https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1577795
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 6.0.1; SM-J120W Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome WebView",
    "version": "58.0.3029.83",
    "major": "58"
  },
  "engine": {
    "name": "Blink",
    "version": "58.0.3029.83"
  },
  "os": {
    "name": "Android",
    "version": "6.0.1"
  },
  "device": {
    "vendor": "Samsung",
    "model": "SM-J120W",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by Satnamathwal94** [comment]
Hello
