### ISSUE TITLE
Uniswap V2 liquidity: Crash report: `Error: invalid BigNumber string (argument="value", value="v2", code=INVALID_ARGUMENT, version=bignumber/5.2.0)`

### ISSUE THREAD

**Issue by dturska12** [Uniswap/uniswap-interface#1973]
## URL
  
https://app.uniswap.org/#/pool/v2

## Error

```
Error: invalid BigNumber string (argument="value", value="v2", code=INVALID_ARGUMENT, version=bignumber/5.2.0)
```

## Stacktrace

```
Error: invalid BigNumber string (argument="value", value="v2", code=INVALID_ARGUMENT, version=bignumber/5.2.0)
    at e.value (https://app.uniswap.org/static/js/4.1f113f4d.chunk.js:2:84695)
    at e.value (https://app.uniswap.org/static/js/4.1f113f4d.chunk.js:2:84839)
    at e.value (https://app.uniswap.org/static/js/4.1f113f4d.chunk.js:2:84918)
    at Function.value (https://app.uniswap.org/static/js/4.1f113f4d.chunk.js:2:256769)
    at WA (https://app.uniswap.org/static/js/main.da319e82.chunk.js:1:592543)
    at no (https://app.uniswap.org/static/js/4.1f113f4d.chunk.js:2:1471320)
    at Vu (https://app.uniswap.org/static/js/4.1f113f4d.chunk.js:2:1523778)
    at _s (https://app.uniswap.org/static/js/4.1f113f4d.chunk.js:2:1510952)
    at As (https://app.uniswap.org/static/js/4.1f113f4d.chunk.js:2:1510880)
    at Ss (https://app.uniswap.org/static/js/4.1f113f4d.chunk.js:2:1510743)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 11; Pixel 4a (5G) Build/RQ3A.210605.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.120 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome WebView",
    "version": "91.0.4472.120",
    "major": "91"
  },
  "engine": {
    "name": "Blink",
    "version": "91.0.4472.120"
  },
  "os": {
    "name": "Android",
    "version": "11"
  },
  "device": {
    "model": "Pixel 4a (5G)",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by christianbm1** [comment]
Getting the same error.

**Comment by BOR4** [comment]
way to reproduce:
1. go to app.uniswap.org
2. click pool
3. click more
4. click v2 liquidity
