### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by nitish22688** [Uniswap/uniswap-interface#1997]
Steps:

- Navigate to Add liquidity page.
- Select ETH token

Issue: Crash with below message

## URL
  
https://app.uniswap.org/#/add/ETH/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.499580c4.chunk.js:2:86932)
    at t.r.sortsBefore (https://app.uniswap.org/static/js/4.499580c4.chunk.js:2:75669)
    at https://app.uniswap.org/static/js/main.c36b7687.chunk.js:1:318725
    at Object._o [as useMemo] (https://app.uniswap.org/static/js/4.499580c4.chunk.js:2:1477438)
    at t.useMemo (https://app.uniswap.org/static/js/4.499580c4.chunk.js:2:1396910)
    at _O (https://app.uniswap.org/static/js/main.c36b7687.chunk.js:1:318698)
    at Xv (https://app.uniswap.org/static/js/main.c36b7687.chunk.js:1:360004)
    at no (https://app.uniswap.org/static/js/4.499580c4.chunk.js:2:1472705)
    at zo (https://app.uniswap.org/static/js/4.499580c4.chunk.js:2:1482272)
    at Vu (https://app.uniswap.org/static/js/4.499580c4.chunk.js:2:1526154)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "91.0.4472.124",
    "major": "91"
  },
  "engine": {
    "name": "Blink",
    "version": "91.0.4472.124"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by justindomingue** [comment]
#1763
