### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by LiquityLife** [Uniswap/uniswap-interface#2103]
## URL
  
https://app.uniswap.org/#/swap?use=V2

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9"
  },
  "independentField": "INPUT",
  "typedValue": "99999999999999999999999999999999999999999999999999999999999",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.bc934aa1.chunk.js:2:87112)
    at new t (https://app.uniswap.org/static/js/4.bc934aa1.chunk.js:2:71291)
    at Function.t.fromFractionalAmount (https://app.uniswap.org/static/js/4.bc934aa1.chunk.js:2:71484)
    at t.n.quote (https://app.uniswap.org/static/js/4.bc934aa1.chunk.js:2:74519)
    at B (https://app.uniswap.org/static/js/4.bc934aa1.chunk.js:2:76615)
    at new e (https://app.uniswap.org/static/js/4.bc934aa1.chunk.js:2:245388)
    at Function.e.bestTradeExactIn (https://app.uniswap.org/static/js/4.bc934aa1.chunk.js:2:246786)
    at https://app.uniswap.org/static/js/main.0bec473b.chunk.js:1:169258
    at Object.Ao [as useMemo] (https://app.uniswap.org/static/js/4.bc934aa1.chunk.js:2:1564133)
    at t.useMemo (https://app.uniswap.org/static/js/4.bc934aa1.chunk.js:2:1483605)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "91.0.4472.124",
    "major": "91"
  },
  "engine": {
    "name": "Blink",
    "version": "91.0.4472.124"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by moodysalem** [comment]
caused by inputting an amount that overflows uint256 max

**Comment by willhennessy** [comment]
#2299 @
