### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by diegodorado** [Uniswap/uniswap-interface#2155]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
  },
  "OUTPUT": {
    "currencyId": ""
  },
  "independentField": "INPUT",
  "typedValue": "1",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:95424)
    at new e (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:141451)
    at Function.e.createUncheckedTrade (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:144962)
    at https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:163550
    at Object.To [as useMemo] (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:1665632)
    at t.useMemo (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:1585104)
    at Od (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:163076)
    at qj (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:232973)
    at Wj (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:233341)
    at $T (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:650019)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "91.0.4472.77",
    "major": "91"
  },
  "engine": {
    "name": "Blink",
    "version": "91.0.4472.77"
  },
  "os": {
    "name": "Linux",
    "version": "x86_64"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
thanks for reporting and sorry for the trouble! We're on it. https://github.com/Uniswap/uniswap-interface/issues/2162
