### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by tech-lcx** [Uniswap/uniswap-interface#2158]
## URL
  
https://app.uniswap.org/#/add/0x037A54AaB062628C9Bbae1FDB1583c195585fe41/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/3000

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_B",
  "typedValue": "5000",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "0.04",
  "rightRangeTypedValue": "0.11424"
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:95424)
    at new e (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:141451)
    at Function.e.createUncheckedTrade (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:144962)
    at https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:163550
    at Object.To [as useMemo] (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:1665632)
    at t.useMemo (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:1585104)
    at Od (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:163076)
    at qj (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:232973)
    at Wj (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:233341)
    at Jy (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:422721)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "92.0.4515.131",
    "major": "92"
  },
  "engine": {
    "name": "Blink",
    "version": "92.0.4515.131"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.4"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
thanks for reporting and sorry for the trouble! We're on it. https://github.com/Uniswap/uniswap-interface/issues/2162
