### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by hello-sangwon** [Uniswap/uniswap-interface#2160]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&theme=light&exactAmount=0.1&exactField=output

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  },
  "independentField": "OUTPUT",
  "typedValue": "0.1",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:95424)
    at new e (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:141451)
    at Function.e.createUncheckedTrade (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:144962)
    at https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:163550
    at Object.To [as useMemo] (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:1665632)
    at t.useMemo (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:1585104)
    at Od (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:163076)
    at Pd (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:169110)
    at $T (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:649436)
    at no (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:1660899)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "92.0.4515.107",
    "major": "92"
  },
  "engine": {
    "name": "Blink",
    "version": "92.0.4515.107"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
thanks for reporting and sorry for the trouble! We're on it. https://github.com/Uniswap/uniswap-interface/issues/2162
