### ISSUE TITLE
Crash report: `Error: Invariant failed` (when trying to access V3 pool)

### ISSUE THREAD

**Issue by nickcruz** [Uniswap/uniswap-interface#2162]
## URL
  
https://app.uniswap.org/#/pool/60944

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:95424)
    at new e (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:141451)
    at Function.e.createUncheckedTrade (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:144962)
    at https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:163550
    at Object.To [as useMemo] (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:1665632)
    at t.useMemo (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:1585104)
    at Od (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:163076)
    at qj (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:232973)
    at Xk (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:574460)
    at no (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:1660899)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "92.0.4515.131",
    "major": "92"
  },
  "engine": {
    "name": "Blink",
    "version": "92.0.4515.131"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by nickcruz** [comment]
Looks like this is the same issue as #2161 and #2160 (maybe others). Stacktrace looks almost identical.

**Comment by nickcruz** [comment]
I can repro this when:
- Accessing with metamask installed
- Accessing in private browsing / incognito (Brave)

**Comment by nickcruz** [comment]
Seems to be repro'ing for both closed and out of range USDC/ETH pools that I have:
- Closed: USDC/ETH (https://app.uniswap.org/#/pool/47228)
- Out of range: USDC/ETH (https://app.uniswap.org/#/pool/60944)

However this one seems to be working great:
- In range: UNI/ETH (https://app.uniswap.org/#/pool/47252)

**Comment by tarruda** [comment]
Here's another way to reproduce:

- go to https://app.uniswap.org/#/swap
- select usdc as the second token
- type some value in the usdc token

The crash happens after 3-4 seconds.

**Comment by nickcruz** [comment]
Thanks @justindomingue !!
