### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by abapforgeeks** [Uniswap/uniswap-interface#2163]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0x2b591e99afe9f32eaa6214f7b7629768c40eeb39

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0x2b591e99afE9f32eAA6214f7B7629768c40Eeb39"
  },
  "OUTPUT": {
    "currencyId": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
  },
  "independentField": "INPUT",
  "typedValue": "56000",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:95424)
    at new e (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:141451)
    at Function.e.createUncheckedTrade (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:144962)
    at https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:163550
    at Object.To [as useMemo] (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:1665632)
    at t.useMemo (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:1585104)
    at Od (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:163076)
    at qj (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:232973)
    at Wj (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:233341)
    at $T (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:650039)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "92.0.4515.107",
    "major": "92"
  },
  "engine": {
    "name": "Blink",
    "version": "92.0.4515.107"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
thanks for reporting and sorry for the trouble! We're on it. https://github.com/Uniswap/uniswap-interface/issues/2162
