### ISSUE TITLE
Crash report: `Error: Invariant failed` (when trying to swap dai with sUSD)

### ISSUE THREAD

**Issue by kylekaplan** [Uniswap/uniswap-interface#2164]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
  },
  "OUTPUT": {
    "currencyId": "0x8c6f28f2F1A3C87F0f938b96d27520d9751ec8d9"
  },
  "independentField": "INPUT",
  "typedValue": "77.62",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:95424)
    at new e (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:141451)
    at Function.e.createUncheckedTrade (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:144962)
    at https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:163550
    at Object.To [as useMemo] (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:1665632)
    at t.useMemo (https://app.uniswap.org/static/js/4.759c9e49.chunk.js:2:1585104)
    at Od (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:163076)
    at qj (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:232973)
    at Wj (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:233341)
    at $T (https://app.uniswap.org/static/js/main.2f8b5aec.chunk.js:1:650019)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "92.0.4515.131",
    "major": "92"
  },
  "engine": {
    "name": "Blink",
    "version": "92.0.4515.131"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
thanks for reporting and sorry for the trouble! We're on it. https://github.com/Uniswap/uniswap-interface/issues/2162
