### ISSUE TITLE
Crash report: `TypeError: Cannot read property '0xdd1e14a6d699c4e893b14203b13d596e3e53d874dd59f7f6082869f5884d39aa' of undefined`

### ISSUE THREAD

**Issue by MarcinSPro** [Uniswap/uniswap-interface#2183]
## URL
  
https://cowswap.exchange/#/play

## Error

```
TypeError: Cannot read property '0xdd1e14a6d699c4e893b14203b13d596e3e53d874dd59f7f6082869f5884d39aa' of undefined
```

## Stacktrace

```
TypeError: Cannot read property '0xdd1e14a6d699c4e893b14203b13d596e3e53d874dd59f7f6082869f5884d39aa' of undefined
    at https://cowswap.exchange/static/js/main.040695c8.chunk.js:1:221462
    at https://cowswap.exchange/static/js/4.88b069e3.chunk.js:2:211805
    at https://cowswap.exchange/static/js/4.88b069e3.chunk.js:2:212311
    at Kd.a.id (https://cowswap.exchange/static/js/main.040695c8.chunk.js:1:221237)
    at Kd (https://cowswap.exchange/static/js/main.040695c8.chunk.js:1:221472)
    at Wb (https://cowswap.exchange/static/js/main.040695c8.chunk.js:1:249523)
    at ro (https://cowswap.exchange/static/js/4.88b069e3.chunk.js:2:2386621)
    at Js (https://cowswap.exchange/static/js/4.88b069e3.chunk.js:2:2439079)
    at Su (https://cowswap.exchange/static/js/4.88b069e3.chunk.js:2:2426253)
    at xu (https://cowswap.exchange/static/js/4.88b069e3.chunk.js:2:2426181)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "92.0.4515.107",
    "major": "92"
  },
  "engine": {
    "name": "Blink",
    "version": "92.0.4515.107"
  },
  "os": {
    "name": "Linux",
    "version": "x86_64"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by moodysalem** [comment]
This is from the cowswap interface which is a fork
