### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by ekotysh** [Uniswap/uniswap-interface#2186]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&theme=dark&exactAmount=20&exactField=output

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  },
  "independentField": "OUTPUT",
  "typedValue": "20",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:95424)
    at new e (https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:141451)
    at Function.e.createUncheckedTrade (https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:144962)
    at https://app.uniswap.org/static/js/main.e432ba44.chunk.js:1:163607
    at Object.To [as useMemo] (https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1665632)
    at t.useMemo (https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1585104)
    at Od (https://app.uniswap.org/static/js/main.e432ba44.chunk.js:1:163111)
    at Pd (https://app.uniswap.org/static/js/main.e432ba44.chunk.js:1:169189)
    at $T (https://app.uniswap.org/static/js/main.e432ba44.chunk.js:1:649608)
    at no (https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1660899)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "91.0.4472.77",
    "major": "91"
  },
  "engine": {
    "name": "Blink",
    "version": "91.0.4472.77"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.14.6"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by moodysalem** [comment]
fixed by https://github.com/Uniswap/uniswap-interface/commit/f463df97bf59ca7af92a7a0b314bd0a9d178bef5 currently being deployed, should work in 5-10 minutes
