### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by kodyyuen** [Uniswap/uniswap-interface#2192]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&theme=dark&exactAmount=0.27&exactField=output

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  },
  "independentField": "OUTPUT",
  "typedValue": "0.27",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:95424)
    at new e (https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:141451)
    at Function.e.createUncheckedTrade (https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:144962)
    at https://app.uniswap.org/static/js/main.e432ba44.chunk.js:1:163607
    at Object.To [as useMemo] (https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1665632)
    at t.useMemo (https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1585104)
    at Od (https://app.uniswap.org/static/js/main.e432ba44.chunk.js:1:163111)
    at Pd (https://app.uniswap.org/static/js/main.e432ba44.chunk.js:1:169189)
    at $T (https://app.uniswap.org/static/js/main.e432ba44.chunk.js:1:649608)
    at no (https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1660899)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "92.0.4515.131",
    "major": "92"
  },
  "engine": {
    "name": "Blink",
    "version": "92.0.4515.131"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by hanabi62513** [comment]
わからないもっとわかりやすく
あたしの資産はどこ？

2021年8月11日(水) 14:14 kodyyuen ***@***.***>:

**Comment by hanabi62513** [comment]
これじゃ英語で分かりませんもっと分かりやすく教えて txt のことですか W がつけるんですか

2021年8月11日(水) 14:14 kodyyuen ***@***.***>:
