### ISSUE TITLE
Crash report: `TypeError: Cannot read property '0x899f1fad6727428f45744941e415ebda5214bd061240df272da2fc704124aa6b' of undefined`

### ISSUE THREAD

**Issue by includeleec** [Uniswap/uniswap-interface#2203]
## URL
  
https://cowswap.exchange/#/swap

## `swap` state
    
```json
{
  "independentField": "INPUT",
  "typedValue": "",
  "INPUT": {
    "currencyId": ""
  },
  "OUTPUT": {
    "currencyId": ""
  },
  "recipient": null
}
```

## Error

```
TypeError: Cannot read property '0x899f1fad6727428f45744941e415ebda5214bd061240df272da2fc704124aa6b' of undefined
```

## Stacktrace

```
TypeError: Cannot read property '0x899f1fad6727428f45744941e415ebda5214bd061240df272da2fc704124aa6b' of undefined
    at https://cowswap.exchange/static/js/main.76ae2db9.chunk.js:1:221548
    at https://cowswap.exchange/static/js/4.7b5aabe1.chunk.js:2:212057
    at https://cowswap.exchange/static/js/4.7b5aabe1.chunk.js:2:212563
    at Yd.a.id (https://cowswap.exchange/static/js/main.76ae2db9.chunk.js:1:221323)
    at Yd (https://cowswap.exchange/static/js/main.76ae2db9.chunk.js:1:221558)
    at Bb (https://cowswap.exchange/static/js/main.76ae2db9.chunk.js:1:249991)
    at ro (https://cowswap.exchange/static/js/4.7b5aabe1.chunk.js:2:2389542)
    at Js (https://cowswap.exchange/static/js/4.7b5aabe1.chunk.js:2:2442000)
    at Su (https://cowswap.exchange/static/js/4.7b5aabe1.chunk.js:2:2429174)
    at xu (https://cowswap.exchange/static/js/4.7b5aabe1.chunk.js:2:2429102)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "89.0.4389.128",
    "major": "89"
  },
  "engine": {
    "name": "Blink",
    "version": "89.0.4389.128"
  },
  "os": {
    "name": "Mac OS",
    "version": "11.4.0"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by moodysalem** [comment]
This error is from the cowswap interface
