### ISSUE TITLE
Crash report: `Error: Unsupported chain ID`

### ISSUE THREAD

**Issue by Cubimickey** [Uniswap/uniswap-interface#2205]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": ""
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
Error: Unsupported chain ID
```

## Stacktrace

```
Error: Unsupported chain ID
    at n.get (https://app.uniswap.org/static/js/main.5691fd30.chunk.js:1:68192)
    at cd (https://app.uniswap.org/static/js/main.5691fd30.chunk.js:1:158460)
    at Nd (https://app.uniswap.org/static/js/main.5691fd30.chunk.js:1:165625)
    at Ud (https://app.uniswap.org/static/js/main.5691fd30.chunk.js:1:166155)
    at Bd (https://app.uniswap.org/static/js/main.5691fd30.chunk.js:1:168212)
    at eA (https://app.uniswap.org/static/js/main.5691fd30.chunk.js:1:649763)
    at no (https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1660899)
    at zo (https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1670466)
    at Vu (https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1714348)
    at Ss (https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1700531)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "92.0.4515.131",
    "major": "92"
  },
  "engine": {
    "name": "Blink",
    "version": "92.0.4515.131"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by moodysalem** [comment]
must be connected to a network other than one of our supported chains
https://github.com/Uniswap/uniswap-interface/blob/422c703e71c7fbfd6ad6c96723d3e8c98f7309de/src/constants/tokens.ts#L153
