### ISSUE TITLE
Crash report: `Error: Unsupported chain ID`

### ISSUE THREAD

**Issue by vishalsachdev** [Uniswap/uniswap-interface#2256]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": ""
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
Error: Unsupported chain ID
```

## Stacktrace

```
Error: Unsupported chain ID
    at n.get (https://app.uniswap.org/static/js/main.9ac9ee28.chunk.js:1:68119)
    at cd (https://app.uniswap.org/static/js/main.9ac9ee28.chunk.js:1:158435)
    at Nd (https://app.uniswap.org/static/js/main.9ac9ee28.chunk.js:1:165600)
    at Ud (https://app.uniswap.org/static/js/main.9ac9ee28.chunk.js:1:166130)
    at Bd (https://app.uniswap.org/static/js/main.9ac9ee28.chunk.js:1:168187)
    at tA (https://app.uniswap.org/static/js/main.9ac9ee28.chunk.js:1:669886)
    at no (https://app.uniswap.org/static/js/3.8ff246f0.chunk.js:2:1667565)
    at zo (https://app.uniswap.org/static/js/3.8ff246f0.chunk.js:2:1677132)
    at Vu (https://app.uniswap.org/static/js/3.8ff246f0.chunk.js:2:1721014)
    at Ss (https://app.uniswap.org/static/js/3.8ff246f0.chunk.js:2:1707197)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "92.0.4515.159",
    "major": "92"
  },
  "engine": {
    "name": "Blink",
    "version": "92.0.4515.159"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
What chain were you connected to? app.uniswap.org only supports a limited number of chain IDs
* Ethereum mainnet and testnets
* Optimism mainnet and testnet
* Arbitrum mainnet and testnet

If your wallet is connected to a different chain like Polygon, you will receive this error message. 

Can you try connecting to one of the supported chains and re-open if this issue still appears?
