### ISSUE TITLE
Crash report: `TypeError: t.replaceAll is not a function`

### ISSUE THREAD

**Issue by ChaY20** [Uniswap/uniswap-interface#2293]
## URL
  
https://app.uniswap.org/#/vote

## Error

```
TypeError: t.replaceAll is not a function
```

## Stacktrace

```
TypeError: t.replaceAll is not a function
    at https://app.uniswap.org/static/js/main.7837411f.chunk.js:1:475667
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.7837411f.chunk.js:1:475130
    at Object.To [as useMemo] (https://app.uniswap.org/static/js/3.0ff11e5a.chunk.js:2:1672802)
    at https://app.uniswap.org/static/js/3.0ff11e5a.chunk.js:2:1592274
    at Vw (https://app.uniswap.org/static/js/main.7837411f.chunk.js:1:475043)
    at Gw (https://app.uniswap.org/static/js/main.7837411f.chunk.js:1:476402)
    at EA (https://app.uniswap.org/static/js/main.7837411f.chunk.js:1:670375)
    at no (https://app.uniswap.org/static/js/3.0ff11e5a.chunk.js:2:1668069)
    at zo (https://app.uniswap.org/static/js/3.0ff11e5a.chunk.js:2:1677636)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 4.4.2; HUAWEI Y541-U02) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "81.0.4044.138",
    "major": "81"
  },
  "engine": {
    "name": "Blink",
    "version": "81.0.4044.138"
  },
  "os": {
    "name": "Android",
    "version": "4.4.2"
  },
  "device": {
    "model": "HUAWEI Y541-U02",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
@NoahZinsmeister we received 3 reports of this error on the Vote page in the last four days. Was it introduced in the Bravo upgrade?

#2306 #2295
