### ISSUE TITLE
Crash report: `TypeError: t.replaceAll is not a function`

### ISSUE THREAD

**Issue by maarlen** [Uniswap/uniswap-interface#2295]
## URL
  
https://app.uniswap.org/#/vote

## Error

```
TypeError: t.replaceAll is not a function
```

## Stacktrace

```
TypeError: t.replaceAll is not a function
    at https://app.uniswap.org/static/js/main.2e1918bd.chunk.js:1:475846
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.2e1918bd.chunk.js:1:475309
    at Object.To [as useMemo] (https://app.uniswap.org/static/js/3.819e44f4.chunk.js:2:1673704)
    at https://app.uniswap.org/static/js/3.819e44f4.chunk.js:2:1593176
    at Vw (https://app.uniswap.org/static/js/main.2e1918bd.chunk.js:1:475222)
    at Gw (https://app.uniswap.org/static/js/main.2e1918bd.chunk.js:1:476581)
    at EA (https://app.uniswap.org/static/js/main.2e1918bd.chunk.js:1:670645)
    at no (https://app.uniswap.org/static/js/3.819e44f4.chunk.js:2:1668971)
    at zo (https://app.uniswap.org/static/js/3.819e44f4.chunk.js:2:1678538)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 8.0.0; SAMSUNG-SM-G930A Build/R16NW; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.110 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome WebView",
    "version": "70.0.3538.110",
    "major": "70"
  },
  "engine": {
    "name": "Blink",
    "version": "70.0.3538.110"
  },
  "os": {
    "name": "Android",
    "version": "8.0.0"
  },
  "device": {
    "vendor": "Samsung",
    "model": "SM-G930A",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
thanks, merging with https://github.com/Uniswap/uniswap-interface/issues/2293
