### ISSUE TITLE
Crash report: `Error: deferred error during ABI decoding triggered accessing index 8`

### ISSUE THREAD

**Issue by shaoguos** [Uniswap/uniswap-interface#2298]
## URL
  
https://lqku6-wqaaa-aaaad-qalmq-cai.ic.fleek.co/#/vote

## Error

```
Error: deferred error during ABI decoding triggered accessing index 8
```

## Stacktrace

```
Error: deferred error during ABI decoding triggered accessing index 8
    at O (https://lqku6-wqaaa-aaaad-qalmq-cai.ic.fleek.co/static/js/4.806c3d88.chunk.js:2:607745)
    at Array.get (https://lqku6-wqaaa-aaaad-qalmq-cai.ic.fleek.co/static/js/4.806c3d88.chunk.js:2:615775)
    at m (https://lqku6-wqaaa-aaaad-qalmq-cai.ic.fleek.co/static/js/4.806c3d88.chunk.js:2:80161)
    at b (https://lqku6-wqaaa-aaaad-qalmq-cai.ic.fleek.co/static/js/4.806c3d88.chunk.js:2:80280)
    at v (https://lqku6-wqaaa-aaaad-qalmq-cai.ic.fleek.co/static/js/4.806c3d88.chunk.js:2:80560)
    at new e (https://lqku6-wqaaa-aaaad-qalmq-cai.ic.fleek.co/static/js/4.806c3d88.chunk.js:2:80628)
    at n.<anonymous> (https://lqku6-wqaaa-aaaad-qalmq-cai.ic.fleek.co/static/js/4.806c3d88.chunk.js:2:159523)
    at new n (https://lqku6-wqaaa-aaaad-qalmq-cai.ic.fleek.co/static/js/4.806c3d88.chunk.js:2:607148)
    at e.value (https://lqku6-wqaaa-aaaad-qalmq-cai.ic.fleek.co/static/js/4.806c3d88.chunk.js:2:616246)
    at https://lqku6-wqaaa-aaaad-qalmq-cai.ic.fleek.co/static/js/main.b50380e6.chunk.js:1:470938
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "93.0.4577.63",
    "major": "93"
  },
  "engine": {
    "name": "Blink",
    "version": "93.0.4577.63"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by moodysalem** [comment]
diff domain
