### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by mttrinh2494** [Uniswap/uniswap-interface#2302]
## URL
  
https://beta.sheepdex.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0x5032d4f51A4D0278504BBdcaCB24f61CAd384DC8"
  },
  "OUTPUT": {
    "currencyId": "0x5D47B6E7Edfc82E2ecd481b3Db70d0F6600FdEf8"
  },
  "independentField": "INPUT",
  "typedValue": "1",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://beta.sheepdex.org/static/js/4.46fcde47.chunk.js:2:80650)
    at new t (https://beta.sheepdex.org/static/js/main.b2154c91.chunk.js:1:4461)
    at Function.t.fromFractionalAmount (https://beta.sheepdex.org/static/js/main.b2154c91.chunk.js:1:4654)
    at t.n.quote (https://beta.sheepdex.org/static/js/main.b2154c91.chunk.js:1:7657)
    at R (https://beta.sheepdex.org/static/js/main.b2154c91.chunk.js:1:9910)
    at e.get (https://beta.sheepdex.org/static/js/main.b2154c91.chunk.js:1:545651)
    at https://beta.sheepdex.org/static/js/main.b2154c91.chunk.js:1:1061205
    at Object.ha [as useMemo] (https://beta.sheepdex.org/static/js/4.46fcde47.chunk.js:2:1381868)
    at t.useMemo (https://beta.sheepdex.org/static/js/4.46fcde47.chunk.js:2:1302783)
    at mR (https://beta.sheepdex.org/static/js/main.b2154c91.chunk.js:1:1061169)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "93.0.4577.63",
    "major": "93"
  },
  "engine": {
    "name": "Blink",
    "version": "93.0.4577.63"
  },
  "os": {
    "name": "Windows",
    "version": "7"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
it looks like this error report is from a fork of uniswap,  beta.sheepdex.org/#/swap

let me know if I'm mistaken!
