### ISSUE TITLE
Crash report: `TypeError: t.replaceAll is not a function`

### ISSUE THREAD

**Issue by JulesLecuir** [Uniswap/uniswap-interface#2306]
## URL
  
https://app.uniswap.org/#/vote

## Error

```
TypeError: t.replaceAll is not a function
```

## Stacktrace

```
TypeError: t.replaceAll is not a function
    at https://app.uniswap.org/static/js/main.aa46409c.chunk.js:1:488931
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.aa46409c.chunk.js:1:488416
    at Object.To [as useMemo] (https://app.uniswap.org/static/js/3.4087c00c.chunk.js:2:1661571)
    at https://app.uniswap.org/static/js/3.4087c00c.chunk.js:2:1581043
    at Ww (https://app.uniswap.org/static/js/main.aa46409c.chunk.js:1:488139)
    at Hw (https://app.uniswap.org/static/js/main.aa46409c.chunk.js:1:489895)
    at RA (https://app.uniswap.org/static/js/main.aa46409c.chunk.js:1:684470)
    at no (https://app.uniswap.org/static/js/3.4087c00c.chunk.js:2:1656838)
    at zo (https://app.uniswap.org/static/js/3.4087c00c.chunk.js:2:1666405)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 8.0.0; ONEPLUS A3003) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "81.0.4044.138",
    "major": "81"
  },
  "engine": {
    "name": "Blink",
    "version": "81.0.4044.138"
  },
  "os": {
    "name": "Android",
    "version": "8.0.0"
  },
  "device": {
    "vendor": "OnePlus",
    "model": "A3003",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
thanks, merging with https://github.com/Uniswap/uniswap-interface/issues/2293
