### ISSUE TITLE
Crash report: `TypeError: s.flatMap is not a function`

### ISSUE THREAD

**Issue by eizi12** [Uniswap/uniswap-interface#2319]
## URL
  
https://app.uniswap.org/#/swap?use=V2&outputCurrency=0xFAA118dE5456c888F05aB173286a81Bc82Cb7635

## `swap` state
    
```json
{
  "independentField": "INPUT",
  "typedValue": "",
  "INPUT": {
    "currencyId": null
  },
  "OUTPUT": {
    "currencyId": null
  },
  "recipient": null
}
```

## Error

```
TypeError: s.flatMap is not a function
```

## Stacktrace

```
TypeError: s.flatMap is not a function
    at https://app.uniswap.org/static/js/main.f9f0d330.chunk.js:1:172193
    at Object.useMemo (https://app.uniswap.org/static/js/3.4087c00c.chunk.js:2:1662803)
    at push.t.useMemo (https://app.uniswap.org/static/js/3.4087c00c.chunk.js:2:1581043)
    at ad (https://app.uniswap.org/static/js/main.f9f0d330.chunk.js:1:172171)
    at Ud (https://app.uniswap.org/static/js/main.f9f0d330.chunk.js:1:178883)
    at push.859.E.maxHops (https://app.uniswap.org/static/js/main.f9f0d330.chunk.js:1:181010)
    at zd (https://app.uniswap.org/static/js/main.f9f0d330.chunk.js:1:181404)
    at oA (https://app.uniswap.org/static/js/main.f9f0d330.chunk.js:1:664911)
    at no (https://app.uniswap.org/static/js/3.4087c00c.chunk.js:2:1656838)
    at Vu (https://app.uniswap.org/static/js/3.4087c00c.chunk.js:2:1709296)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 11; M2102J20SG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "88.0.4324.152",
    "major": "88"
  },
  "engine": {
    "name": "Blink",
    "version": "88.0.4324.152"
  },
  "os": {
    "name": "Android",
    "version": "11"
  },
  "device": {
    "model": "M2102J20SG",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
closing in favor of https://github.com/Uniswap/uniswap-interface/issues/2300
