### ISSUE TITLE
Crash report: `TypeError: $(...).slider is not a function`

### ISSUE THREAD

**Issue by JinChi2199** [Uniswap/uniswap-interface#2331]
## URL
  
https://app.herofi.io/#/mycharacter

## Error

```

```

## Stacktrace

```
TypeError: $(...).slider is not a function
    at https://app.herofi.io/static/js/main.24b21237.chunk.js:1:358086
    at Nu (https://app.herofi.io/static/js/4.e2fe000a.chunk.js:1:1819844)
    at t.unstable_runWithPriority (https://app.herofi.io/static/js/4.e2fe000a.chunk.js:1:1837657)
    at qi (https://app.herofi.io/static/js/4.e2fe000a.chunk.js:1:1760015)
    at ju (https://app.herofi.io/static/js/4.e2fe000a.chunk.js:1:1819305)
    at https://app.herofi.io/static/js/4.e2fe000a.chunk.js:1:1819216
    at L (https://app.herofi.io/static/js/4.e2fe000a.chunk.js:1:1836716)
    at MessagePort.k.port1.onmessage (https://app.herofi.io/static/js/4.e2fe000a.chunk.js:1:1835438)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "93.0.4577.63",
    "major": "93"
  },
  "engine": {
    "name": "Blink",
    "version": "93.0.4577.63"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by justindomingue** [comment]
@JinChi2199 url is app.herofi.io. Closing.
